defaults:
  - _self_

seed: 4242
input_model_id: NbAiLab/nb-bert-large
output_model_id: alexandrainst/nbailab-large-nli-scandi
wandb_run_name: nb-bert-large-nli-scandi
push_to_hub: True
batch_size: 2
patience: 100
learning_rate: 2e-5
max_steps: 50_000
warmup_ratio: 0.01
logging_steps: 100
eval_steps: 100
save_steps: 100
save_total_limit: 1
checkpoint:

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models

train_datasets:
  da:
    - id: data/processed/danfever
      subset:
      split: train
      premise_column: evidence_extract
      hypothesis_column: claim
      label_column: label
      label_names:
        contradiction: Refuted
        entailment: Supported
        neutral: NotEnoughInfo

    - id: KBLab/overlim
      subset: mnli_da
      split: train
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction

    - id: KBLab/overlim
      subset: cb_da
      split: train
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        contradiction: contradiction
        neutral: neutral

  sv:
    - id: KBLab/overlim
      subset: mnli_sv
      split: train
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction

    - id: KBLab/overlim
      subset: cb_sv
      split: train
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        contradiction: contradiction
        neutral: neutral

    - id: MoritzLaurer/multilingual-NLI-26lang-2mil7
      subset:
      split: sv_fever
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction

    - id: MoritzLaurer/multilingual-NLI-26lang-2mil7
      subset:
      split: sv_anli
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction

  nb:
    - id: KBLab/overlim
      subset: mnli_nb
      split: train
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction

    - id: KBLab/overlim
      subset: cb_nb
      split: train
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        contradiction: contradiction
        neutral: neutral

val_datasets:
  da:
    - id: data/processed/danfever
      subset:
      split: val
      premise_column: evidence_extract
      hypothesis_column: claim
      label_column: label
      label_names:
        contradiction: Refuted
        entailment: Supported
        neutral: NotEnoughInfo
  sv:
    - id: KBLab/overlim
      subset: mnli_sv
      split: validation
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction
  nb:
    - id: KBLab/overlim
      subset: mnli_nb
      split: validation
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction

test_datasets:
  da:
    - id: data/processed/danfever
      subset:
      split: test
      premise_column: evidence_extract
      hypothesis_column: claim
      label_column: label
      label_names:
        contradiction: Refuted
        entailment: Supported
        neutral: NotEnoughInfo
  sv:
    - id: KBLab/overlim
      subset: mnli_sv
      split: test
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction
  nb:
    - id: KBLab/overlim
      subset: mnli_nb
      split: test
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction

dataset_proportions:
  da: 0.3334
  sv: 0.3333
  nb: 0.3333
