defaults:
  - _self_
  - model: nb-bert-large
  - dataset: scandi

seed: 4242
use_wandb: True
push_to_hub: True
patience: 100
learning_rate: 2e-5
max_steps: 50_000
warmup_ratio: 0.01
logging_steps: 100
eval_steps: 100
save_steps: 100
save_total_limit: 1
checkpoint:

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models
