defaults:
  - _self_
  - model: ai-sweden-roberta-large
  - dataset: scandi

seed: 4242
use_wandb: True
push_to_hub: True
patience: 10
learning_rate: 2e-5
max_steps: 50_000
warmup_steps: 1_000
logging_steps: 100
eval_steps: 1_000
save_steps: 1_000
total_batch_size: 128
save_total_limit: 1
checkpoint:

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models

evaluation:
  model_id:
  batch_size:
  languages:
    - da
    - sv
    - nb

test_datasets:
  da:
    - id: data/processed/danfever
      subset:
      split: test
      premise_column: evidence_extract
      hypothesis_column: claim
      label_column: label
      label_names:
        contradiction: Refuted
        entailment: Supported
        neutral: NotEnoughInfo
  sv:
    - id: KBLab/overlim
      subset: mnli_sv
      split: test
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction
  nb:
    - id: KBLab/overlim
      subset: mnli_nb
      split: test
      premise_column: premise
      hypothesis_column: hypothesis
      label_column: label
      label_names:
        entailment: entailment
        neutral: neutral
        contradiction: contradiction
